import numpy as np
from ..Elements import Elements
from .BaseIntegrals import BaseIntegrals

class DispersionQuad(BaseIntegrals):
    """
    Dispersion Analytical formulas with respect to changing only a quadrupole
    """
    
    def ni_sum(self, Ei:Elements, Ej: Elements):
        """ 
        Calculates the dispersion in Ei generated by dipoles Ej in the ring 
        using the definition of dispersion with dipoles being the source of it.
        """
        Ijc1 = self.Ijc1_L(Ej) 
        Ijs1 = self.Ijs1_L(Ej) 
        Rij_t = self.Rab_thin(Ei, Ej)
        Tij_t = self.Tab_thin(Ei, Ej)
        return np.sum(Ej.BendB*(Ijc1*Rij_t+Ijs1*Tij_t), axis = Ej._bAxis)
        

    def dni_dqk_integral(self, Ei: Elements, Ek: Elements):
        """
        
        New Integral formula deduced to calculate the derivative of dispersion
        with respect to changing a quadrupole
                        
        Based on thin response for dispersion from a quadrupole and integrating
        Dispersion along the element even if it has bending.
        In bpm i due to quadrupole (or combined function dipole) 0
    
        This method is better when not applying fringe field corrections!
        
        
        """
        
        #TODO: check etrance correction into dipoles due to quadrupole fringe and
        #see if it improves results.

        Cik1 = self.Cabn(Ei, Ek, 1)
        Sik1 = self.Sabn(Ei, Ek, 1)
        
        Ik0  = self.Ik0(Ek)
        Ikc1 = self.Ikc1(Ek)
        Iks1 = self.Iks1(Ek)
        Ikc2 = self.Ikc2(Ek)
        Iks2 = self.Iks2(Ek)
        
        disp_k      = Ek.dispersionB
        ddisp_k     = Ek.dispersionpB
        source = 0
        if hasattr(Ek, "Bend"):
            source      = Ek.BendB/(Ek.LengthB*Ek.KB)
        #disp term
        term_1 = Cik1*(Ik0 + Ikc2)/2 + Ek.alphaB*Sik1*(Ik0-Ikc2)/2 + (Ek.alphaB*Cik1 + Sik1)*Iks2/2
        #disp' term
        term_2 = Ek.betaB*(Cik1*Iks2/2 + Sik1*(Ik0 - Ikc2)/2) 
        #Source term 
        term_3 = 0*Sik1
        if hasattr(Ek, "Bend"):
            term_3 = Ek.betaB * Ek.LengthB * (Ikc1*Cik1 + Iks1*Sik1) - term_1

        #OBSERVATION: the 1/L_k is already inside the definition of the Ik0, etc, terms!
        
        dni_dqk = np.sqrt(Ei.betaB/Ek.betaB)/(2*np.sin(np.pi*self.tune))*(
            disp_k*term_1 + ddisp_k*term_2 + source*term_3)
        
        return -np.real(dni_dqk)
    
    def dRij_dqk_thick23_disp(self, Ei : Elements, Ej : Elements, Ek : Elements):
        """Computes the dRij_dqk dispersion term, which is relevant in the HORIZONTAL direction

        THIS formula only applies for all Ek.
        """

        Ej2 = Elements(self.ring, self.all_optics, Ej._ind -1, self.dir_ind, self.sgn)
        Ej2.broadcasters(Ej._bAxis, Ej._ndim)
        dni_dqk = self.dni_dqk_integral(Ei, Ek)
        dnj_dqk = self.dni_dqk_integral(Ej, Ek)  # This is the derivative at the entrance!
        ddnj_ds_dqk = (dnj_dqk-  self.dni_dqk_integral(Ej2, Ek))/Ej2.LengthB
        
        if not hasattr(Ej, 'avDispersion'):
            Ej.average()

        #TODO: The derivative with respect to the MCF has to be added, but it is a long integral of disp^2 inside the quadrupoles
        
        ana_dORM_dq_disp = -(dni_dqk *Ej.avDispersionB +(dnj_dqk + ddnj_ds_dqk*Ej.LengthB/2)*Ei.dispersionB ) / (self.mcf * self.circumference)
        
        return np.real(ana_dORM_dq_disp)
    
    def dni_dqk_sum(self, Ei : Elements, Ej: Elements, Ek: Elements):
        """ 
        
        Zeus legacy function
        
        Derivative of the dispersions in Ei with respect to given quadrupole
        strengths Ek considering Ej dipoles in the ring... VALIDATED!!
        #TODO: LACKS THE derivative with respect to integral terms!
        
        """
    
        Cij1 = self.Cabn(Ei, Ej, 1)
        Cik2 = self.Cabn(Ei, Ek, 2)
        Cjk2 = self.Cabn(Ej, Ek, 2)
        Sij1 = self.Sabn(Ei, Ej, 1)
        Sik2 = self.Sabn(Ei, Ek, 2)
        Sjk2 = self.Sabn(Ej, Ek, 2)
        
        #Terms for the thick quadrupole formula      
        
        Ik0  = self.Ik0(Ek)
        Iks2 = self.Iks2(Ek)
        Ikc2 = self.Ikc2(Ek)
        SSik2= Ikc2*Sik2-Iks2*Cik2
        SSjk2= Ikc2*Sjk2-Iks2*Cjk2
        CCik2= Ikc2*Cik2+Iks2*Sik2
        CCjk2= Ikc2*Cjk2+Iks2*Sjk2

        #Terms for the dipoles, if they are CFD consider it as well through KB
    
        if (hasattr(Ej, "Bend")):
            Ijc1 = self.Ikc1(Ej)
            Ijs1 = self.Iks1(Ej)
        else:
            Ijc1 = self.Ikc1_(Ej)
            Ijs1 = self.Iks1_(Ej)        

        dRij_terms =  (Cij1 * ( CCik2 + CCjk2 + 2*Ik0 *np.cos(np.pi * self.tune)**2) + 
                       Sij1 * ( SSik2 - SSjk2 + Ik0*np.sin(2*np.pi*self.tune)*(2*np.heaviside(Ei.muB-Ek.muB, 0)
                           -2*np.heaviside(Ej.muB-Ek.muB, 0)-np.sign(Ei.muB-Ej.muB)))) 
        dTij_terms = (Sij1 * ( CCik2 - CCjk2 + 2*Ik0 *np.cos(np.pi * self.tune)**2) + 
                      Cij1 * ( -SSjk2 - SSik2 + Ik0*np.sin(2*np.pi*self.tune)*(-2*np.heaviside(Ei.muB-Ek.muB, 0)
                           +2*np.heaviside(Ej.muB-Ek.muB, 0)+np.sign(Ei.muB-Ej.muB)))) 
        
        
        
        
        dni_dqk =  -((Ej.BendB * np.sqrt(Ei.betaB * Ej.betaB)) 
         / (8 * np.sin(np.pi * self.tune)* np.sin(2 * np.pi * self.tune)) 
         * (Ijc1 * dRij_terms + Ijs1 * dTij_terms))
        
        return np.real(np.sum(dni_dqk, axis = Ej._bAxis))
    
    #Dispersion terms in the horizontal 
    
    def dRij_dqk_thick23_disp_old(self, Ei : Elements, Ej : Elements, Ek : Elements, El : Elements):
        """
        
        Zeus legacy function
        
        Old formula for computing the derivative of dispersion using the definition
        Computes the dRij_dqk dispersion term, which is relevant in the HORIZONTAL
        transverse dimension, neglecting the derivative with respect to the mcf
        
        Ei: BPMs,         1
        Ej: correctors,   2
        Ek: quadrupoles,  0
        El: dipoles       3
        THIS formula only applies for all Ek.
        """
        
        dni_dqk = np.squeeze(self.dni_dqk_sum(Ei, El, Ek))[:, :, None]
        dnj_dqk = np.squeeze(self.dni_dqk_sum(Ej, El, Ek))[:, None, :] # This is the derivative at the entrance!
        
        Ei.broadcasters(1, 3)
        Ej.broadcasters(2, 3)
        Ek.broadcasters(0, 3)
        
        if not hasattr(Ej, 'avDispersion'):
            Ej.average()
        # 2. FIXED: Added the mandatory MINUS sign for the RF cavity response
        ana_dORM_dq_disp = (dni_dqk *Ej.avDispersionB +dnj_dqk *Ei.dispersionB ) / (self.mcf * self.circumference)
        
        return np.real(ana_dORM_dq_disp)
        
