import numpy as np
from ..Elements import Elements
from .BaseIntegrals import BaseIntegrals

class Dispersion(BaseIntegrals):
    """
    Dispersion Analytical formulas and Jacobians
    """
    
    def ni_sum(self, Ei:Elements, Ej: Elements):
        """ 
        Calculates the dispersion in Ei generated by dipoles Ej in the ring 
        using the definition of dispersion with dipoles being the source of it.
        """
        Ijc1 = self.Ijc1_L(Ej) 
        Ijs1 = self.Ijs1_L(Ej) 
        Rij_t = self.Rab_thin(Ei, Ej)
        Tij_t = self.Tab_thin(Ei, Ej)
        return np.sum(Ej.BendB*(Ijc1*Rij_t+Ijs1*Tij_t), axis = Ej._bAxis)
        
    def dni_dqk_integral(self, Ei: Elements, Ek: Elements):
        """
        
        New Integral formula deduced to calculate the derivative of dispersion
        with respect to changing a quadrupole
                        
        Based on thin response for dispersion from a quadrupole and integrating
        Dispersion along the element even if it has bending.
        In bpm i due to quadrupole (or combined function dipole) 0
    
        """
        #This method is better when not applying fringe field corrections.

        Cik1 = self.Cabn(Ei, Ek, 1)
        Sik1 = self.Sabn(Ei, Ek, 1)
        
        if hasattr(Ek, "K") and Ek.K[0] !=0:
            Ik0  = self.Ik0(Ek)
            Ikc1 = self.Ikc1(Ek)
            Iks1 = self.Iks1(Ek)
            Ikc2 = self.Ikc2(Ek)
            Iks2 = self.Iks2(Ek)
            
        else :
            Ik0  = self.Ik0_(Ek)
            Ikc1 = self.Ikc1_(Ek)
            Iks1 = self.Iks1_(Ek)
            Ikc2 = self.Ikc2_(Ek)
            Iks2 = self.Iks2_(Ek)
        
        disp_k      = Ek.dispersionB
        ddisp_k     = Ek.dispersionpB
        source = 0
        if hasattr(Ek, "Bend"):
            source      = Ek.BendB/(Ek.LengthB*Ek.KB)
        #disp term
        term_1 = Cik1*(Ik0 + Ikc2)/2 + Ek.alphaB*Sik1*(Ik0-Ikc2)/2 + (Ek.alphaB*Cik1 + Sik1)*Iks2/2
        #disp' term
        term_2 = Ek.betaB*(Cik1*Iks2/2 + Sik1*(Ik0 - Ikc2)/2) 
        #Source term 
        term_3 = 0*Sik1 #Like this to have the right dimensions.
        if hasattr(Ek, "Bend"):
            term_3 = Ek.betaB * Ek.LengthB * (Ikc1*Cik1 + Iks1*Sik1) - term_1

        #OBSERVATION: the 1/L_k is already inside the definition of the Ik0, etc, terms!
        
        dni_dqk = np.sqrt(Ei.betaB/Ek.betaB)/(2*np.sin(np.pi*self.tune))*(
            disp_k*term_1 + ddisp_k*term_2 + source*term_3)
        
        return -np.real(dni_dqk)
    
    
    
    def dni_dqk_sum(self, Ei : Elements, Ej: Elements, Ek: Elements):
        """ 
        
        Zeus legacy function
        
        Derivative of the dispersions in Ei with respect to given quadrupole
        strengths Ek considering Ej dipoles in the ring... VALIDATED!!
        #TODO: LACKS THE derivative with respect to integral terms!
        
        """
    
        Cij1 = self.Cabn(Ei, Ej, 1)
        Cik2 = self.Cabn(Ei, Ek, 2)
        Cjk2 = self.Cabn(Ej, Ek, 2)
        Sij1 = self.Sabn(Ei, Ej, 1)
        Sik2 = self.Sabn(Ei, Ek, 2)
        Sjk2 = self.Sabn(Ej, Ek, 2)
        
        #Terms for the thick quadrupole formula      
        
        Ik0  = self.Ik0(Ek)
        Iks2 = self.Iks2(Ek)
        Ikc2 = self.Ikc2(Ek)
        SSik2= Ikc2*Sik2-Iks2*Cik2
        SSjk2= Ikc2*Sjk2-Iks2*Cjk2
        CCik2= Ikc2*Cik2+Iks2*Sik2
        CCjk2= Ikc2*Cjk2+Iks2*Sjk2

        #Terms for the dipoles, if they are CFD consider it as well through KB
    
        if (hasattr(Ej, "Bend")):
            Ijc1 = self.Ikc1(Ej)
            Ijs1 = self.Iks1(Ej)
        else:
            Ijc1 = self.Ikc1_(Ej)
            Ijs1 = self.Iks1_(Ej)        

        dRij_terms =  (Cij1 * ( CCik2 + CCjk2 + 2*Ik0 *np.cos(np.pi * self.tune)**2) + 
                       Sij1 * ( SSik2 - SSjk2 + Ik0*np.sin(2*np.pi*self.tune)*(2*np.heaviside(Ei.muB-Ek.muB, 0)
                           -2*np.heaviside(Ej.muB-Ek.muB, 0)-np.sign(Ei.muB-Ej.muB)))) 
        dTij_terms = (Sij1 * ( CCik2 - CCjk2 + 2*Ik0 *np.cos(np.pi * self.tune)**2) + 
                      Cij1 * ( -SSjk2 - SSik2 + Ik0*np.sin(2*np.pi*self.tune)*(-2*np.heaviside(Ei.muB-Ek.muB, 0)
                           +2*np.heaviside(Ej.muB-Ek.muB, 0)+np.sign(Ei.muB-Ej.muB)))) 
        
        
        
        
        dni_dqk =  -((Ej.BendB * np.sqrt(Ei.betaB * Ej.betaB)) 
         / (8 * np.sin(np.pi * self.tune)* np.sin(2 * np.pi * self.tune)) 
         * (Ijc1 * dRij_terms + Ijs1 * dTij_terms))
        
        return np.real(np.sum(dni_dqk, axis = Ej._bAxis))
    
    def dni_dhk_sex_term_simple(self, Ei:Elements, Ej: Elements, El: Elements, i , j):
        """
        Simplified sextupole feedback term for thin sextupoles
        Based on the simple formula that the derivative is eta* Rij * dq
        """
        dq  = (i + j* El.LengthB/2)*2*El.SB
        dRij = self.dRij_dqk_thick23(Ei, Ej, El)
        disp = El.dispersionB + El.dispersionpB*El.LengthB/2
        
        return np.sum(np.real(dq *dRij*disp * Ej.LengthB), axis=El._bAxis)
    
    def dni_dhk_sex_term(self, Ei:Elements, Ej: Elements, El: Elements, i , j):
        """
        sextupole feedback term without feedback
        
        Ei: BPMs
        Ej: changed dipoles
        Ek: sextupoles

        """
        
        #General cosinus terms
        Cij1 = self.Cabn(Ei, Ej, 1)
        Sij1 = self.Sabn(Ei, Ej, 1)

        #Terms for thick sextupoles and mixing integrals
        Sil2 = self.Sabn(Ei, El, 2)
        Cil2 = self.Cabn(Ei, El, 2)
        Sjl2 = self.Sabn(Ej, El, 2)
        Cjl2 = self.Cabn(Ej, El, 2)
        
        Il0  = self.I_disp_l0_nf(El, i, j)
        Ilc2 = self.I_disp_lc2_nf(El, i, j) 
        Ils2 = self.I_disp_ls2_nf(El, i, j)
        
        SSil2 = np.sum(Ilc2*Sil2 - Ils2*Cil2, axis = El._bAxis, keepdims=True)
        CCil2 = np.sum(Ilc2*Cil2 + Ils2*Sil2, axis = El._bAxis, keepdims=True)
        DDil2 = np.sum(Il0*np.heaviside(Ei.muB-El.muB, 0), axis = El._bAxis, keepdims=True)

        SSjl2 = np.sum(Ilc2*Sjl2 - Ils2*Cjl2, axis = El._bAxis, keepdims=True)
        CCjl2 = np.sum(Ilc2*Cjl2 + Ils2*Sjl2, axis = El._bAxis, keepdims=True)
        DDjl2 = np.sum(Il0*np.heaviside(Ej.muB-El.muB, 0), axis = El._bAxis, keepdims=True)
        
        Iij0 = np.sum(Il0, axis = El._bAxis, keepdims=True)
        
        #Terms for thick correctors without quadrupole moment inside of them

        Ijc1_L = self.Ikc1_(Ej)
        Ijs1_L = self.Iks1_(Ej)
    
        
        dRij_terms =  (Cij1 * ( CCil2 + CCjl2 + 2*Iij0 *np.cos(np.pi * self.tune)**2) + 
                    Sij1 * ( SSil2 - SSjl2 
                    + np.sin(2*np.pi*self.tune)*(2*DDil2 - 2*DDjl2 - Iij0*np.sign(Ei.muB-Ej.muB)))) 
        
        dTij_terms = (Sij1 * (CCil2 - CCjl2 + 2*Iij0 * np.cos(np.pi * self.tune)**2) + 
                    Cij1 * (-SSjl2 - SSil2 
                    + np.sin(2*np.pi*self.tune)*(-2*DDil2 + 2*DDjl2 + Iij0*np.sign(Ei.muB-Ej.muB)))) 

        
        result = self.sgn * ( np.sqrt(Ei.betaB * Ej.betaB) 
        / (8 * np.sin(np.pi * self.tune)* np.sin(2 * np.pi * self.tune)) 
        * (Ijc1_L * dRij_terms + Ijs1_L * dTij_terms))
        
        return np.real(np.sum(result, axis = El._bAxis))
        
        
    def dni_dhk_feedback(self, Ei:Elements, Ej: Elements, Ek: Elements, delta, kicks, dni_de, dRikde, dRijde):
        """
        Calculates the change in dispersion in Ei due to changing a dipole Ek
        in the ring considering the active feedback by correctors Ej for a
        nominal change in the quadrupole component in CFDs
        
        delta: energy_derivative
        """
        geometry = Ek.BendB / Ek.KB
        
        term1 = self.dni_dqk_integral
        
        term2 = geometry*dRikde
        
        term3 = kicks@dRijde
        
        term4 = dni_de*delta
        
        return term1 + term2 + term3 + term4     
        
    
    